systems = [
    "PC", 
    "G64", 
    "TES", 
    "Master V", 
    "Gameling", 
    "Vena Gear", 
    "Vena Oasis", 
    "Super TES", 
    "Playsistem", 
    "TES 64", 
    "DreamVast", 
    "Playsystem 2", 
    "mBox", 
    "Game Sphere", 
    "GS", 
    "PPS", 
    "mBox 360", 
    "Nuu", 
    "Playsystem 3", 
    "grPhone", 
    "grPad", 
    "mPad", 
    "Wuu", 
    "OYA", 
    "mBox One", 
    "Playsystem 4", 
    "mBox Next", 
    "Playsystem 5"
]
