topics = [
    'Abstract',
    'Airplane',
    'Aliens',
    'Alternate History',
    'Assassin',
    'Business',
    'City',
    'Colonization',
    'Comedy',
    'Construction',
    'Cooking',
    'Crime',
    'Cyberpunk',
    'Dance',
    'Detective',
    'Disasters',
    'Dungeon',
    'Dystopian',
    'Evolution',
    'Expedition',
    'Extreme Sports',
    'Fantasy',
    'Farming',
    'Fashion',
    'Game Dev',
    'Government',
    'Hacking',
    'History',
    'Horror',
    'Hospital',
    'Hunting',
    'Law',
    'Life',
    'Mad Science',
    'Martial Arts',
    'Medieval',
    'Military',
    'Movies',
    'Music',
    'Mystery',
    'Mythology',
    'Ninja',
    'Pirate',
    'Post Apocalyptic',
    'Prison',
    'Racing',
    'Romance',
    'Rhythm',
    'School',
    'Sci-fi',
    'Space',
    'Sports',
    'Spy',
    'Superheroes',
    'Surgery',
    'Technology',
    'Thief',
    'Time Travel',
    'Transport',
    'Ufo',
    'Vampire',
    'Virtual Pet',
    'Vocabulary',
    'Werewolf',
    'Wild West',
    'Zombies',
]
