topics = [
    'Airplane',
    'Aliens',
    'Alternate History',
    'Business',
    'City',
    'Comedy',
    'Cyberpunk',
    'Dance',
    'Detective',
    'Dungeon',
    'Evolution',
    'Fantasy',
    'Fashion',
    'Game Dev',
    'Government',
    'Hacking',
    'History',
    'Horror',
    'Hospital',
    'Hunting',
    'Law',
    'Life',
    'Martial Arts',
    'Medieval',
    'Military',
    'Movies',
    'Music',
    'Mystery',
    'Ninja',
    'Pirate',
    'Post Apocalyptic',
    'Prison',
    'Racing',
    'Rhythm',
    'Romance',
    'School',
    'Sci-fi',
    'Space',
    'Sports',
    'Spy',
    'Superheroes',
    'Surgery',
    'Time Travel',
    'Transport',
    'Ufo',
    'Vampire',
    'Virtual Pet',
    'Vocabulary',
    'Werewolf',
    'Wild West',
    'Zombies',
]
